name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y g++ make cmake  

      - name: Install Google Test
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          cmake -S . -B build
          cmake --build build
          sudo cmake --install build

      - name: Debug file structure
        run: ls -R

      - name: Build project
        run: |
          if [ -d "tests" ]; then
            make -C tests
          elif [ -d "Assignment 1/tests" ]; then
            make -C "Assignment 1/tests"
          else
            echo "::error::Tests directory not found!"
            exit 1
          fi

      - name: Run tests
        run: |
          if [ -d "tests" ]; then
            make -C tests test
          elif [ -d "Assignment 1/tests" ]; then
            make -C "Assignment 1/tests" test
          fi
