name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y g++ make cmake libeigen3-dev 

      - name: Install Google Test
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          cmake -S . -B build
          cmake --build build
          sudo cmake --install build

      - name: Build and run tests (Assignment1)
        run: |
          make -C Assignment1  # Сборка
          make -C Assignment1 test  # Запуск тестов 
      - name: Build and run tests (Assignment2)
        run: |
          make -C Assignment2
          make -C Assignment2 test
